.PHONY: any
all:
	./VMTranslator BasicTest.vm
	./VMTranslator StaticTest.vm
	./VMTranslator StackTest.vm
	./VMTranslator PointerTest.vm
	./VMTranslator SimpleAdd.vm
debug:
	./VMTranslator MemoryAccess/BasicTest/BasicTest.vm
	./VMTranslator MemoryAccess/StaticTest/StaticTest.vm
	./VMTranslator StackArithmetic/StackTest/StackTest.vm
	./VMTranslator MemoryAccess/PointerTest/PointerTest.vm
	./VMTranslator StackArithmetic/SimpleAdd/SimpleAdd.vm
